2023-06-23 14:43:58,948 INFO    MainThread:50856 [wandb_setup.py:_flush():68] Configure stats pid to 50856
2023-06-23 14:43:58,948 INFO    MainThread:50856 [wandb_setup.py:_flush():68] Loading settings from /Users/visriv/.config/wandb/settings
2023-06-23 14:43:58,949 INFO    MainThread:50856 [wandb_setup.py:_flush():68] Loading settings from /Users/visriv/Documents/Git/xai-seq/wandb/settings
2023-06-23 14:43:58,949 INFO    MainThread:50856 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-06-23 14:43:58,949 INFO    MainThread:50856 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-23 14:43:58,949 INFO    MainThread:50856 [wandb_init.py:_log_setup():492] Logging user logs to /Users/visriv/Documents/Git/xai-seq/wandb/run-20230623_144358-wd9h6t9o/logs/debug.log
2023-06-23 14:43:58,949 INFO    MainThread:50856 [wandb_init.py:_log_setup():493] Logging internal logs to /Users/visriv/Documents/Git/xai-seq/wandb/run-20230623_144358-wd9h6t9o/logs/debug-internal.log
2023-06-23 14:43:58,950 INFO    MainThread:50856 [wandb_init.py:init():532] calling init triggers
2023-06-23 14:43:58,950 INFO    MainThread:50856 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-06-23 14:43:58,950 INFO    MainThread:50856 [wandb_init.py:init():588] starting backend
2023-06-23 14:43:58,951 INFO    MainThread:50856 [wandb_init.py:init():592] setting up manager
2023-06-23 14:43:58,970 ERROR   MainThread:50856 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "/Users/visriv/Library/Python/3.9/lib/python/site-packages/wandb/sdk/wandb_init.py", line 1133, in init
    run = wi.init()
  File "/Users/visriv/Library/Python/3.9/lib/python/site-packages/wandb/sdk/wandb_init.py", line 593, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/visriv/Library/Python/3.9/lib/python/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/visriv/Library/Python/3.9/lib/python/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/visriv/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/visriv/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/visriv/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/visriv/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
